Accepting pull requests?
cstenglein/raspiblitz-web pull request #17
Opened 2021-07-16 12:46 UTC by blackcoffeexbt

Hi Christoph,

This looks like a really nice project you're working on at the moment. Are you accepting pull requests? I've made a few minor changes to the UI to improve the layout slightly here and there. You've done a huge amount of work on this so far but if you're accepting small changes like this I'm happy to help. 

I'm on Twitter - @blackcoffeebtc
My email is randommw@protonmail.com

2021-07-16 17:16 UTC, cstenglein requested changes

2021-07-16 17:16 UTC, cstenglein commented on src/container/ModalDialog/ModalDialog.tsx
> +        <div className='px-5 pb-10'>{props.children}</div>
I'm not sure about that padding

Looks a bit weird with the e.g. the change password dialog

![image](https://user-images.githubusercontent.com/9399034/125984557-ac30b9db-9104-4b60-9956-95c1611c8c48.png)

2021-07-16 17:16 UTC, cstenglein commented on src/container/ModalDialog/ModalDialog.tsx
> +        <div className='flex pr-1'>
Looks nice, but i think it would look even better with 

```suggestion
        <div className='flex pr-2 pt-1'>
```

2021-07-16 17:18 UTC, cstenglein commented
Hi @blackcoffeexbt 

thanks for your contribution! Really appreciate it if someone else gives me feedback - or like you - contributes, so yes, PRs are appreciated! :)

I've got one suggestion and one thing to thing we should think about how to make it nicer (the pb-10 in the dialog)

Otherwise it really looks good, thank you! :+1:

2021-07-19 09:22 UTC, blackcoffeexbt commented
I've updated pull request. The bottom margin of the `ChangePwModal.tsx` component has been removed to display it better within the modal with a bottom padding. The height of the `AppCard.tsx` component has been tweaked to h-full to display all cards with the same height.

2021-07-19 18:02 UTC, cstenglein reviewed
Thank you for the changes!

Still not happy about the `pb-10` though 😅

Hope we can find a good solution for that.

Other than that, great work! :)

2021-07-19 18:02 UTC, cstenglein commented on src/components/SettingsComponents/ChangePwModal/ChangePwModal.tsx
> +        <div className='mt-5 flex flex-col justify-center text-center items-center'>
With the change on pb-10 that would look weird

depending on what we are doing with pb-10, I would revert that to it's previous state

```suggestion
        <div className='my-5 flex flex-col justify-center text-center items-center'>
```

2021-09-08 17:08 UTC, merged

2021-09-08 17:09 UTC, cstenglein commented
Hi @blackcoffeexbt 

There were some merge conflicts so I resolved them by hand. So it could be that some changes were lost due to that but I think most made it through :)

Thank you very much and sorry that it took so long!