refactor(home): unlock modal
cstenglein/raspiblitz-web pull request #777
Opened 2024-09-26 10:26 UTC by escapedcat

2024-10-04 21:25 UTC, cstenglein commented
Will merge this after 1.11.3

Too big to check this before Release, sorry :(

2024-10-05 08:39 UTC, escapedcat commented
No worries, understandable

2024-10-05 09:12 UTC, cstenglein requested changes
Wow, really awesome :rocket: 

Must have been tons of work, thank you :+1: 

There is only one thing which would be cool:

in mobile, the `receive` and `send` tabs should be vertical, so they can be read:

https://nextui.org/docs/components/tabs#vertical

![Screenshot 2024-10-05 at 11-07-04 RaspiBlitz - myBlitz](https://github.com/user-attachments/assets/165fc000-f0d2-4386-b90a-08cffde9d3d4)

2024-10-05 15:52 UTC, cstenglein approved these changes

2024-10-05 15:55 UTC, merged